import { VehicleDto } from '@dtos/vehicle.dto';

export const mockVehicules: VehicleDto[] = [
  {
    vehicleId: 1,
    price: 25000,
    year: 2021,
    brand: 'Tesla',
    model: 'Model 3',
    category: 'Compact',
    type: 'Electric',
    autonomy: 500,
    batteryCapacity: 75,
    maxChargingPower: 11,
    chargingTime: 8,
    seatsCount: 5,
    imageUrl: 'none',
  },
  {
    vehicleId: 2,
    price: 20000,
    year: 2020,
    brand: 'Nissan',
    model: 'Leaf',
    category: 'Compact',
    type: 'Electric',
    autonomy: 250,
    batteryCapacity: 40,
    maxChargingPower: 6.6,
    chargingTime: 7,
    seatsCount: 5,
    imageUrl: 'none',
  },
  {
    vehicleId: 3,
    price: 30000,
    year: 2020,
    brand: 'Chevrolet',
    model: 'Bolt EV',
    category: 'Compact',
    type: 'Electric',
    autonomy: 300,
    batteryCapacity: 60,
    maxChargingPower: 7.2,
    chargingTime: 6,
    seatsCount: 5,
    imageUrl: 'none',
  },
  {
    vehicleId: 4,
    price: 15000,
    year: 2019,
    brand: 'Renault',
    model: 'Zoe',
    category: 'Compact',
    type: 'Electric',
    autonomy: 250,
    batteryCapacity: 41,
    maxChargingPower: 7.4,
    chargingTime: 5,
    seatsCount: 5,
    imageUrl: 'none',
  },
  {
    vehicleId: 5,
    price: 35000,
    year: 2019,
    brand: 'Audi',
    model: 'e-Tron',
    category: 'Compact',
    type: 'Electric',
    autonomy: 300,
    batteryCapacity: 95,
    maxChargingPower: 11,
    chargingTime: 8,
    seatsCount: 5,
    imageUrl: 'none',
  },
  {
    vehicleId: 6,
    price: 40000,
    year: 2022,
    brand: 'Ford',
    model: 'Mustang Mach-E',
    category: 'Compact',
    type: 'Electric',
    autonomy: 350,
    batteryCapacity: 88,
    maxChargingPower: 11.2,
    chargingTime: 8,
    seatsCount: 5,
    imageUrl: 'none',
  },
  {
    vehicleId: 7,
    price: 30000,
    year: 2020,
    brand: 'Hyundai',
    model: 'Kona Electric',
    category: 'SUV',
    type: 'Electric',
    autonomy: 400,
    batteryCapacity: 64,
    maxChargingPower: 6.6,
    chargingTime: 7,
    seatsCount: 5,
    imageUrl: 'none',
  },
  {
    vehicleId: 8,
    price: 45000,
    year: 2021,
    brand: 'Porsche',
    model: 'Taycan',
    category: 'Sport',
    type: 'Electric',
    autonomy: 250,
    batteryCapacity: 79,
    maxChargingPower: 9.6,
    chargingTime: 6,
    seatsCount: 4,
    imageUrl: 'none',
  },
  {
    vehicleId: 9,
    price: 35000,
    year: 2020,
    brand: 'Volkswagen',
    model: 'ID.4',
    category: 'SUV',
    type: 'Electric',
    autonomy: 250,
    batteryCapacity: 77,
    maxChargingPower: 11,
    chargingTime: 8,
    seatsCount: 5,
    imageUrl: 'none',
  },
];
